import {armorType, itemsEquipedProps, weaponType} from './types';

export const itemsMock = [
    {
        id: 20001,
        nombre: 'Cuchillo cazador',
        tipo: 'arma',
        rama: '',
        ramaEvo: 0,
        ruta: 'weapon/sas/cuchilloCazador',
        rareza: 0,
        evolucion: '',
        precio: 0,
        ataque: 0,
        danio_elemento01: 0,
        elemento_01: 'Fuego',
        elemento01: '',
        danio_elemento02: 0,
        elemento_02: '',
        elemento02: '',
        afilado: '',
        afinidad: 10,
        defensa: 3,
        sello_ancianos: '',
        ranura01: '',
        ranura02: '',
        ranura03: '',
        tipo_vial: '',
        danio_vial: 0,
        elemento_vial: '',
        numero_disparos: 0,
        tipo_disparo: '',
        nota01: '',
        nota02: '',
        nota03: '',
        modificaciones: 0,
        desvio: '',
        tiro_especial: '',
        bonus_kinsecto: '',
        vial01: '',
        vial02: '',
        vial03: '',
        vial04: '',
        vial05: '',
    },
    {
        id: 20002,
        nombre: 'Kys Hazak',
        tipo: 'arma',
        rama: '',
        ramaEvo: 0,
        ruta: 'weapon/gs/kysHazak',
        rareza: 0,
        evolucion: '',
        precio: 0,
        ataque: 0,
        danio_elemento01: 0,
        elemento_01: 'Agua',
        elemento01: '',
        danio_elemento02: 0,
        elemento_02: '',
        elemento02: '',
        afilado: '',
        afinidad: 10,
        defensa: 10,
        sello_ancianos: '',
        ranura01: '',
        ranura02: '',
        ranura03: '',
        tipo_vial: '',
        danio_vial: 0,
        elemento_vial: '',
        numero_disparos: 0,
        tipo_disparo: '',
        nota01: '',
        nota02: '',
        nota03: '',
        modificaciones: 0,
        desvio: '',
        tiro_especial: '',
        bonus_kinsecto: '',
        vial01: '',
        vial02: '',
        vial03: '',
        vial04: '',
        vial05: '',
    },
    {
        id: 20003,
        nombre: 'Filo Wyvern "Hoja"',
        tipo: 'arma',
        rama: '',
        ramaEvo: 0,
        ruta: 'weapon/ls/filoWyvernHoja',
        rareza: 0,
        evolucion: '',
        precio: 0,
        ataque: 0,
        danio_elemento01: 0,
        elemento_01: '',
        elemento01: '',
        danio_elemento02: 0,
        elemento_02: '',
        elemento02: '',
        afilado: '',
        afinidad: 10,
        defensa: 10,
        sello_ancianos: '',
        ranura01: '',
        ranura02: '',
        ranura03: '',
        tipo_vial: '',
        danio_vial: 0,
        elemento_vial: '',
        numero_disparos: 0,
        tipo_disparo: '',
        nota01: '',
        nota02: '',
        nota03: '',
        modificaciones: 0,
        desvio: '',
        tiro_especial: '',
        bonus_kinsecto: '',
        vial01: '',
        vial02: '',
        vial03: '',
        vial04: '',
        vial05: '',
    },
    {
        id: 1,
        nombre: 'Yelmo de Anja',
        tipo: 'casco',
        ruta: 'armor/yelmoAnja',
        rama: 'Cuero',
        rango: 'bajo',
        nivel: 1,
        rareza: 1,
        defensa: 10,
        ranura01: '',
        ranura02: '',
        ranura03: '',
        fuego: 5,
        agua: 2,
        rayo: 3,
        hielo: 5,
        draco: 1,
        precio: 100,
        habilidad1: 'hola',
        habilidad2: 'hola',
    },
    {
        id: 2,
        nombre: 'Yelmo de Rathian',
        ruta: 'armor/yelmoRathian',
        tipo: 'casco',
        rama: 'Cuero',
        rango: 'bajo',
        nivel: 1,
        rareza: 1,
        defensa: 2,
        ranura01: '',
        ranura02: '',
        ranura03: '',
        fuego: 2,
        agua: 4,
        rayo: 2,
        hielo: 2,
        draco: 2,
        precio: 100,
        habilidad1: 'hola',
        habilidad2: 'hola',
    },
    {
        id: 3,
        nombre: 'Cota de Anja',
        ruta: 'armor/cotaAnja',
        tipo: 'Pechera',
        rama: 'Aleación',
        rango: 'bajo',
        nivel: 1,
        rareza: 1,
        defensa: 2,
        ranura01: '',
        ranura02: '',
        ranura03: '',
        fuego: 2,
        agua: 2,
        rayo: 4,
        hielo: 5,
        draco: 5,
        precio: 100,
        habilidad1: 'hola',
        habilidad2: 'hola',
    },
    {
        id: 4,
        nombre: 'Brazales de Anja',
        ruta: 'armor/brazalesAnja',
        tipo: 'guanteletes',
        rama: 'Cuero',
        rango: 'bajo',
        nivel: 1,
        rareza: 1,
        defensa: 2,
        ranura01: '',
        ranura02: '',
        ranura03: '',
        fuego: 5,
        agua: 5,
        rayo: 5,
        hielo: 5,
        draco: 5,
        precio: 100,
        habilidad1: 'hola',
        habilidad2: 'hola',
    },
    {
        id: 5,
        nombre: 'Faja de Anja',
        ruta: 'armor/fajaAnja',
        tipo: 'cintura',
        rama: 'Cuero',
        rango: 'bajo',
        nivel: 1,
        rareza: 1,
        defensa: 2,
        ranura01: '',
        ranura02: '',
        ranura03: '',
        fuego: 1,
        agua: 10,
        rayo: 1,
        hielo: 1,
        draco: 5,
        precio: 100,
        habilidad1: 'hola',
        habilidad2: 'hola',
    },
    {
        id: 6,
        nombre: 'Grebas de Anja',
        ruta: 'armor/grebasAnja',
        tipo: 'grebas',
        rama: 'Cuero',
        rango: 'bajo',
        nivel: 1,
        rareza: 1,
        defensa: 2,
        ranura01: '',
        ranura02: '',
        ranura03: '',
        fuego: 5,
        agua: 5,
        rayo: 5,
        hielo: 5,
        draco: 5,
        precio: 100,
        habilidad1: 'hola',
        habilidad2: 'hola',
    },
];
export const itemsEquippedDefault = {
    arma: {
        id: 20000,
        nombre: '',
        tipo: 'arma',
        rama: '',
        ramaEvo: 0,
        ruta: '',
        rareza: 0,
        evolucion: '',
        precio: 0,
        ataque: 0,
        danio_elemento01: 0,
        elemento_01: '',
        elemento01: '',
        danio_elemento02: 0,
        elemento_02: '',
        elemento02: '',
        afilado: '',
        afinidad: 0,
        defensa: 0,
        sello_ancianos: '',
        ranura01: '',
        ranura02: '',
        ranura03: '',
        tipo_vial: '',
        danio_vial: 0,
        elemento_vial: '',
        numero_disparos: 0,
        tipo_disparo: '',
        nota01: '',
        nota02: '',
        nota03: '',
        modificaciones: 0,
        desvio: '',
        tiro_especial: '',
        bonus_kinsecto: '',
        vial01: '',
        vial02: '',
        vial03: '',
        vial04: '',
        vial05: '',
    },
    casco: {
        id: 10000,
        nombre: '',
        ruta: '',
        tipo: '',
        rama: '',
        rango: '',
        nivel: 0,
        rareza: 0,
        defensa: 0,
        ranura01: '',
        ranura02: '',
        ranura03: '',
        fuego: 0,
        agua: 0,
        rayo: 0,
        hielo: 0,
        draco: 0,
        precio: 0,
        habilidad1: '',
        habilidad2: '',
    },
    pechera: {
        id: 10001,
        nombre: '',
        ruta: '',
        tipo: '',
        rama: '',
        rango: '',
        nivel: 0,
        rareza: 0,
        defensa: 0,
        ranura01: '',
        ranura02: '',
        ranura03: '',
        fuego: 0,
        agua: 0,
        rayo: 0,
        hielo: 0,
        draco: 0,
        precio: 0,
        habilidad1: '',
        habilidad2: '',
    },
    guanteletes: {
        id: 10002,
        nombre: '',
        ruta: '',
        tipo: '',
        rama: '',
        rango: '',
        nivel: 0,
        rareza: 0,
        defensa: 0,
        ranura01: '',
        ranura02: '',
        ranura03: '',
        fuego: 0,
        agua: 0,
        rayo: 0,
        hielo: 0,
        draco: 0,
        precio: 0,
        habilidad1: '',
        habilidad2: '',
    },
    cintura: {
        id: 10003,
        nombre: '',
        ruta: '',
        tipo: '',
        rama: '',
        rango: '',
        nivel: 0,
        rareza: 0,
        defensa: 0,
        ranura01: '',
        ranura02: '',
        ranura03: '',
        fuego: 0,
        agua: 0,
        rayo: 0,
        hielo: 0,
        draco: 0,
        precio: 0,
        habilidad1: '',
        habilidad2: '',
    },
    grebas: {
        id: 10004,
        nombre: '',
        ruta: '',
        tipo: '',
        rama: '',
        rango: '',
        nivel: 0,
        rareza: 0,
        defensa: 0,
        ranura01: '',
        ranura02: '',
        ranura03: '',
        fuego: 0,
        agua: 0,
        rayo: 0,
        hielo: 0,
        draco: 0,
        precio: 0,
        habilidad1: '',
        habilidad2: '',
    },
};
export const equipmentStatsDefault = {
    ataque: 0,
    defensa: 0,
    fuego: 0,
    agua: 0,
    rayo: 0,
    hielo: 0,
    draco: 0,
};
export const filterByItemName = (name: string) => (item: any) => {
    return item.nombre
        .toLowerCase()
        .trim()
        .includes(name.toLowerCase().trim());
};

export function checkIfAItemIsEquipped(equipment: any) {
    let check = false;
    for (const itemsEquippedKey in equipment) {
        if (equipment.hasOwnProperty(itemsEquippedKey)) {
            // @ts-ignore
            const itemEquipped = equipment[itemsEquippedKey];
            if (itemEquipped.nombre !== '') {
                check = true;
            }
        }
    }
    return check;
}

export function calculateEquipmentStats(itemsEquipped: itemsEquipedProps) {
  let defenseSum = 0;
  let fireSum = 0;
  let waterSum = 0;
  let thunderSum = 0;
  let iceSum = 0;
  let dracoSum = 0;
  let attackSum = 0;
  for (const key in itemsEquipped) {
    if (itemsEquipped.hasOwnProperty(key)) {
      // FIXME: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'itemsEquipedProps'.

      // @ts-ignore
      const itemEquipped = itemsEquipped[key];
      if (itemEquipped.nombre !== '') {
        if (itemEquipped.tipo !== 'arma') {
          defenseSum += itemEquipped.defensa;
          fireSum += itemEquipped.fuego;
          waterSum += itemEquipped.agua;
          thunderSum += itemEquipped.rayo;
          iceSum += itemEquipped.hielo;
          dracoSum += itemEquipped.draco;
        } else {
          defenseSum += itemEquipped.defensa;
          attackSum += itemEquipped.ataque;
        }
      }
    }
  }
  return {
    ataque: attackSum,
    agua: waterSum,
    draco: dracoSum,
    fuego: fireSum,
    hielo: iceSum,
    rayo: thunderSum,
    defensa: defenseSum,
  };
}

export function removeItem(
    items: (armorType | weaponType)[],
    itemToRemove: armorType | weaponType,
) {
    return items.filter((x) => x.nombre !== itemToRemove.nombre);
}

export const filterByItemTypes = (typesPressed: string[]) => (items: any) => {
    for (const type of typesPressed) {
        if (items.tipo.toLowerCase() === type.toLowerCase()) {
            return items;
        }
    }
};